apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: z6qdhwlxj-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jsmid/rhtap-qe-java-quarkus:b47bc069bd849412ed07d1fa32fc37678aa9c60c@sha256:c178e491718b877ff77591771066ac0046caefb05211369adce47413401a938a
          name: container-image
